# Generated by Django 3.2 on 2021-11-17 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=40, null=True, verbose_name='keyword')),
                ('max_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='max_price')),
                ('min_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='min_price')),
                ('sold_out', models.CharField(blank=True, max_length=20, null=True, verbose_name='sold_out')),
                ('category', models.CharField(blank=True, max_length=20, null=True, verbose_name='category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='id')),
                ('item_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='price')),
                ('item_date', models.DateField(blank=True, null=True, verbose_name='date')),
                ('item_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='name')),
                ('item_buy_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='buy_price')),
                ('item_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='time_limit')),
                ('keyword', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_item', to='GetUsed.search')),
            ],
        ),
    ]
