# Generated by Django 3.2 on 2021-11-18 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetUsed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_date',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='id'),
        ),
    ]
