# Generated by Django 3.2 on 2021-11-18 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GetUsed', '0003_alter_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='keyword',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_item', to='GetUsed.search', to_field='keyword'),
        ),
        migrations.AlterField(
            model_name='search',
            name='keyword',
            field=models.CharField(max_length=40, null=True, unique=True, verbose_name='keyword'),
        ),
    ]
