# Generated by Django 3.2 on 2021-11-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetUsed', '0004_auto_20211118_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='keyword',
            field=models.CharField(max_length=40, null=True, verbose_name='keyword'),
        ),
        migrations.AlterField(
            model_name='search',
            name='keyword',
            field=models.CharField(max_length=40, null=True, verbose_name='keyword'),
        ),
    ]
