# Generated by Django 3.2 on 2021-11-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetUsed', '0005_auto_20211118_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='id'),
        ),
    ]
