# Generated by Django 3.2 on 2021-11-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetUsed', '0007_alter_item_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='id'),
        ),
    ]
