# Generated by Django 3.2 on 2021-11-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetUsed', '0008_alter_item_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_id',
        ),
        migrations.AddField(
            model_name='item',
            name='item_link',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='link'),
        ),
    ]
