# Generated by Django 3.2 on 2021-11-25 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetUsed', '0009_auto_20211124_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('none', '指定なし'), ('computer', 'コンピュータ'), ('books', '本・雑誌'), ('contents', 'ゲーム・音楽・アニメ映画'), ('HomeAppliances', '家電・AV・カメラ'), ('fashion', 'ファッション'), ('beauty', '美容・コスメ・香水'), ('interior', 'インテリア'), ('outdoor', 'スポーツ・レジャー'), ('goods', 'おもちゃ・グッズ'), ('food', '食料'), ('car', '自動車・オートバイ')], default='none', max_length=20, null=True, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Y', 'ヤフオク'), ('M', 'メルカリ'), ('P', 'PayPayフリマ'), ('R', 'ラクマ'), ('H', 'ハードオフ'), ('M', 'モバオク'), ('E', 'ebay'), ('S', 'セカイモン')], max_length=1, null=True, verbose_name='shop'),
        ),
    ]
