# Generated by Django 3.2 on 2021-11-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetUsed', '0011_auto_20211125_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_limit',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='time_limit'),
        ),
    ]
