# Generated by Django 3.2 on 2021-12-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetUsed', '0013_search_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_status',
            field=models.CharField(choices=[('指定なし', '指定なし'), ('売り切れ', '売り切れ'), ('販売中', '販売中')], max_length=10, null=True, verbose_name='status'),
        ),
    ]
